services:
  db:
    image: postgres:15
    container_name: sagrafacile_db
    restart: unless-stopped
    volumes:
      - sagrafacile_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-sagrafacile}
    ports:
      - "${POSTGRES_PORT:-5432}:5432" # Expose DB port for direct access if needed during setup/debug

  backend:
    image: ghcr.io/giacomocap/sagrafacile-api:main
    container_name: sagrafacile_backend
    restart: unless-stopped
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Production # Ensure this is set for production behavior
      # Connection string will be read from this env var by appsettings.json
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=${POSTGRES_DB:-sagrafacile};Username=${POSTGRES_USER:-postgres};Password=${POSTGRES_PASSWORD:-changeme};"
      JWT_SECRET: ${JWT_SECRET}
      JWT_ISSUER: ${JWT_ISSUER:-SagraFacile}
      JWT_AUDIENCE: ${JWT_AUDIENCE:-SagraFacileApp}
      # Add other backend-specific environment variables from .env
      # INITIAL_ADMIN_EMAIL: ${INITIAL_ADMIN_EMAIL}
      # INITIAL_ADMIN_PASSWORD: ${INITIAL_ADMIN_PASSWORD}
    # No ports exposed directly to host; Caddy will proxy

  frontend:
    image: ghcr.io/giacomocap/sagrafacile-frontend:main
    container_name: sagrafacile_frontend
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_BASE_URL: /api # Caddy will route /api to backend
      NODE_ENV: production
    # No ports exposed directly to host; Caddy will proxy

  caddy:
    image: caddy:2-alpine # Using alpine for smaller size
    container_name: sagrafacile_caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp" # For HTTP/3
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile # Mount local Caddyfile
      - sagrafacile_caddy_data:/data   # Persist Caddy's data (certs, etc.)
      - sagrafacile_caddy_config:/config # Persist Caddy's config
    depends_on:
      - backend
      - frontend

volumes:
  sagrafacile_db_data:
  sagrafacile_caddy_data:
  sagrafacile_caddy_config:
